name = "przeprogramowani-website"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

[env.production]
name = "przeprogramowani-website-production"
route = { pattern = "przeprogramowani.pl", zone_name = "przeprogramowani.pl" }
