name = "przeprogramowani-pl"
compatibility_date = "2024-12-10"
pages_build_output_dir = "dist"

[[pages_build_config]]
  build_command = "npm run build"
  destination_dir = "dist"
  root_dir = ""
  build_caching = false