name = "10x-bench"
type = "javascript"
main = "dist/index.html"
compatibility_date = "2024-12-16"

account_id = "eb313d34b48a9aa3c87eb3554e33134d"

[env.production]
route = "10x-bench.pages.dev/*"

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.ts", "src/**/*.tsx", "src/**/*.astro"]

[build.upload]
format = "service-worker"
